//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackWhite.App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GamePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GamePage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackWhite.App.Properties.GamePage", typeof(GamePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已使用 的本地化字符串。
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Msg_Button_Cancel {
            get {
                return ResourceManager.GetString("Msg_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新游戏 的本地化字符串。
        /// </summary>
        internal static string Msg_Button_NewGame {
            get {
                return ResourceManager.GetString("Msg_Button_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Msg_Button_OK {
            get {
                return ResourceManager.GetString("Msg_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总共使用了{0}步 的本地化字符串。
        /// </summary>
        internal static string Msg_Text_Count {
            get {
                return ResourceManager.GetString("Msg_Text_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你成功完成了游戏 的本地化字符串。
        /// </summary>
        internal static string Msg_Text_Finished {
            get {
                return ResourceManager.GetString("Msg_Text_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要开始新游戏吗？ 的本地化字符串。
        /// </summary>
        internal static string Msg_Text_NewGame {
            get {
                return ResourceManager.GetString("Msg_Text_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成！ 的本地化字符串。
        /// </summary>
        internal static string Msg_Title_Finished {
            get {
                return ResourceManager.GetString("Msg_Title_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始新游戏 的本地化字符串。
        /// </summary>
        internal static string Msg_Title_NewGame {
            get {
                return ResourceManager.GetString("Msg_Title_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新游戏 的本地化字符串。
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成 的本地化字符串。
        /// </summary>
        internal static string State_Finished {
            get {
                return ResourceManager.GetString("State_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成中 的本地化字符串。
        /// </summary>
        internal static string State_Preparing {
            get {
                return ResourceManager.GetString("State_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未完成 的本地化字符串。
        /// </summary>
        internal static string State_Unfinished {
            get {
                return ResourceManager.GetString("State_Unfinished", resourceCulture);
            }
        }
    }
}
