//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackWhite.App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StartPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartPage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackWhite.App.Properties.StartPage", typeof(StartPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自由模式 的本地化字符串。
        /// </summary>
        internal static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探索游戏的规律 的本地化字符串。
        /// </summary>
        internal static string Free_Text {
            get {
                return ResourceManager.GetString("Free_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准模式 的本地化字符串。
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用尽可能少的点击次数完成游戏 的本地化字符串。
        /// </summary>
        internal static string Normal_Text {
            get {
                return ResourceManager.GetString("Normal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最优解 的本地化字符串。
        /// </summary>
        internal static string Perfect {
            get {
                return ResourceManager.GetString("Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用尽可能少的点击次数完成游戏，总点击次数不超过方块总数 的本地化字符串。
        /// </summary>
        internal static string Perfect_Text {
            get {
                return ResourceManager.GetString("Perfect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机 的本地化字符串。
        /// </summary>
        internal static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏尺寸 的本地化字符串。
        /// </summary>
        internal static string Size_Label {
            get {
                return ResourceManager.GetString("Size_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        internal static string Start_Button {
            get {
                return ResourceManager.GetString("Start_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时模式 的本地化字符串。
        /// </summary>
        internal static string Timed {
            get {
                return ResourceManager.GetString("Timed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用尽可能少的时间完成游戏 的本地化字符串。
        /// </summary>
        internal static string Timed_Text {
            get {
                return ResourceManager.GetString("Timed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择游戏模式 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
